Repository apache/skywalking-eyes, pull requests merged in 2020-12, with the labels that each got.

#2 Enhance checking/fixing command, more tests, more comment styles
  .github/workflows/license-eye-check.yaml
  .gitignore
  .golangci.yml
  .licenserc.yaml
  license-eye/Makefile
  license-eye/assets/languages.yaml
  license-eye/assets/styles.yaml
  license-eye/commands/header/check.go
  license-eye/internal/logger/log.go
  license-eye/pkg/comments/config.go
  license-eye/pkg/config/config.go
  license-eye/pkg/header/check.go
  license-eye/pkg/header/check_test.go
  license-eye/pkg/header/config.go
  license-eye/pkg/header/fix.go
  license-eye/pkg/header/fix_test.go
  license-eye/test/testdata/.licenserc_for_test_check.yaml
  license-eye/test/testdata/.licenserc_for_test_fix.yaml
  license-eye/test/testdata/include_test/with_license/testcase.go
  license-eye/test/testdata/include_test/with_license/testcase.java
  license-eye/test/testdata/include_test/with_license/testcase.ml
  license-eye/test/testdata/include_test/without_license/testcase.py
Labels: enhancement

#3 Enhance `check` command to automatically skip non-text (binary) files
  .licenserc.yaml
  license-eye/pkg/header/check.go
Labels: enhancement

#4 Refactor the normalizers to increase accuracy and minimize the use of pattern
  .golangci.yml
  .licenserc.yaml
  license-eye/commands/header/check.go
  license-eye/commands/header/fix.go
  license-eye/internal/logger/log.go
  license-eye/pkg/header/check.go
  license-eye/pkg/header/check_test.go
  license-eye/pkg/header/config.go
  license-eye/pkg/header/fix.go
  license-eye/pkg/license/norm.go
  license-eye/pkg/license/norm_test.go
  license-eye/pkg/result.go
Labels: enhancement

#5 Add new feature to review the pull request and suggest adding license headers
  .github/workflows/license-eye-check.yaml
  .licenserc.yaml
  license-eye/commands/header/check.go
  license-eye/go.mod
  license-eye/go.sum
  license-eye/pkg/header/config.go
  license-eye/pkg/header/fix.go
  license-eye/pkg/header/fix_test.go
  license-eye/pkg/review/header.go
Labels: feature

#6 Add licenses for newly-added deps
  dist/LICENSE
  dist/licenses/LICENSE-doublestar.txt
  dist/licenses/LICENSE-go-github.txt
  dist/licenses/LICENSE-golang-oauth2.txt
  dist/licenses/LICENSE-linguist.txt
  dist/licenses/LICENSE-logrus.txt
  dist/licenses/LICENSE-yaml.v3.txt
Labels: chore

#7 Add feature to support spdx-id to ease the configurations
  .licenserc.yaml
  license-eye/Makefile
  license-eye/README.adoc
  license-eye/assets/lcs-templates/Apache-2.0-ASF.txt
  license-eye/assets/lcs-templates/Apache-2.0.txt
  license-eye/pkg/header/check.go
  license-eye/pkg/header/check_test.go
  license-eye/pkg/header/config.go
  license-eye/pkg/header/fix.go
  license-eye/pkg/header/fix_test.go
  license-eye/pkg/review/header.go
  license-eye/test/config_test.go
  license-eye/test/testdata/.licenserc_for_test_check.yaml
  license-eye/test/testdata/.licenserc_for_test_fix.yaml
  license-eye/test/testdata/test-spdx-asf.yaml
  license-eye/test/testdata/test-spdx.yaml
Labels: feature

#8 Add Contact Us for the 1st release.
  README.adoc
  README.md
Labels: documentation

#9 Add more known comment styles
  license-eye/assets/languages.yaml
Labels: enhancement

#11 Shape the quality-eye sub-directory for NGE2E
  README.md
  quality-eye/README.md
Labels: chore

#16 Fix wrong path of Dockerfile in action.yaml
  .asf.yaml
  .golangci.yml
  Makefile
  action.yml
  commands/deps_resolve.go
  commands/header_fix.go
  pkg/comments/config.go
  pkg/deps/golang.go
  pkg/review/header.go
Labels: chore

#17 Finalize 0.1, fix a minor bug, add docs, etc.
  CONTRIBUTING.md
  README.md
  docs/How-to-release.md
  pkg/review/header.go
Labels: chore, documentation
