Repository apache/skywalking-eyes, pull requests merged in 2021-09, with the labels that each got.

#65 Feature: `header fix` supports nextflow files
  assets/languages.yaml
Labels: feature

#66 Fix file extension conflict between RenderScript and Rust
  assets/languages.yaml
Labels: bug, feature

#67 Resolve absolute path in `.gitignore` to relative path
  .gitignore
  pkg/header/config.go
Labels: bug

#68 Honor Python's coding directive
  assets/languages.yaml
  assets/styles.yaml
  pkg/comments/config_test.go
  pkg/header/fix_test.go
Labels: enhancement

#69 feature: support saving dependencies' licenses
  README.md
  commands/deps_resolve.go
Labels: feature

#70 fix the save location problem
  commands/deps_resolve.go
Labels: bug

#71 Enhance Npm Resolver: support recording license contents
  pkg/deps/npm.go
  pkg/deps/npm_test.go
  pkg/deps/result.go
Labels: feature

#72 Remove .tsx from XML language extensions
  assets/languages.yaml
Labels: bug

#73 Add Comment Style for TypeScript language support
  assets/languages.yaml
Labels: bug
