Repository apache/skywalking-eyes, pull requests merged in 2021-08, with the labels that each got.

#51 Enhance NPM dependency resolver to resolve all the dependent packages
  pkg/deps/npm.go
Labels: feature

#50 add feature: support resolving pom.xml for maven
  go.mod
  go.sum
  pkg/deps/golang.go
  pkg/deps/maven.go
  pkg/deps/maven_test.go
  pkg/deps/resolve.go
Labels: feature

#52 Enhance NPM dependency resolver to resolve deprecated license styles
  pkg/deps/npm.go
  pkg/deps/npm_test.go
Labels: enhancement

#55 Fix wrong license identification
  pkg/license/identifier.go
Labels: bug

#57 make the config file configurable
  README.md
  action.yml
Labels: enhancement

#59 Reduce Docker image size and add npm env to resolve npm projects' dependencies
  Dockerfile
Labels: enhancement

#60 header fix: respect user configured license content
  .golangci.yml
  commands/root.go
  pkg/config/config.go
  pkg/deps/golang.go
  pkg/deps/maven.go
  pkg/deps/maven_test.go
  pkg/header/check.go
  pkg/header/config.go
  pkg/header/fix.go
  pkg/header/fix_test.go
  pkg/review/header.go
Labels: bug, chore

#61 Publish snapshot Docker image to GHCR
  .github/workflows/publish-docker.yaml
  Makefile
  README.md
Labels: chore

#62 add comment type to cython declaration
  README.md
  assets/languages.yaml
  test/testdata/include_test/with_license/testcase.pyx
  test/testdata/include_test/without_license/testcase.pyx
Labels: enhancement
