Repository apache/skywalking-eyes, pull requests merged in 2021-07, with the labels that each got.

#36 Fix minor error
  pkg/config/config.go
  pkg/header/check.go
Labels: bug

#37 Add support for MatLab files
  assets/languages.yaml
  assets/styles.yaml
  pkg/license/norm.go
Labels: enhancement

#38 Add support for Smarty template language
  assets/languages.yaml
  assets/styles.yaml
  pkg/license/norm.go
Labels: enhancement

#39 Add support for Twig template language
  assets/languages.yaml
  assets/styles.yaml
  pkg/license/norm.go
Labels: enhancement

#40 Add support for PHP
  README.md
  assets/languages.yaml
  assets/styles.yaml
  pkg/comments/config.go
  pkg/header/fix.go
  pkg/header/fix_test.go
  test/testdata/include_test/with_license/testcase.php
  test/testdata/include_test/without_license/testcase.php
Labels: feature

#42 Add support of apostrophe style comments for PlantUML
  assets/languages.yaml
  assets/styles.yaml
  pkg/license/norm.go
Labels: feature

#43 Fix typescript file license header fix to use SlashAsterisk instead of AngleBrackets
  assets/languages.yaml
Labels: bug

#44 fix some program compatibility issues in Windows
  assets/assets.go
Labels: enhancement

#46 Enhance Go dependency resolver to resolve built-in and non-standard Go modules
  assets/lcs-templates/BSD-2-Clause.txt
  assets/lcs-templates/ISC.txt
  assets/lcs-templates/MPL-2.0.txt
  assets/lcs-templates/WTFPL.txt
  commands/deps_resolve.go
  go.mod
  go.sum
  pkg/deps/golang.go
  pkg/license/identifier.go
  pkg/license/norm.go
Labels: enhancement
