Repository apache/skywalking-eyes, pull requests merged in 2022-06, with the labels that each got.

#111 Lazy initialize GitHub client for comment
  pkg/review/header.go
Labels: bug

#113 Fix grammar mistakes
  README.md
Labels: chore

#114 Add custom license urls for identification
  assets/urls.yaml
  pkg/deps/golang.go
  pkg/deps/jar.go
  pkg/deps/maven.go
  pkg/deps/npm.go
  pkg/deps/resolve.go
  pkg/license/identifier.go
  pkg/license/identifier_test.go
Labels: enhancement

#115 Stablize summary context to perform consistant output
  dist/LICENSE
  pkg/deps/summary.go
Labels: enhancement

#117 Add `excludes` to `license resolve` config
  README.md
  pkg/deps/config.go
  pkg/deps/golang.go
  pkg/deps/maven.go
  pkg/deps/npm.go
  pkg/deps/result.go
Labels: enhancement

#118 Add support for multiple licenses in the header config section
  README.md
  commands/deps_check.go
  commands/deps_resolve.go
  commands/header_check.go
  commands/header_fix.go
  commands/root.go
  pkg/config/config.go
  pkg/review/header.go
  test/config_test.go
  test/testdata/multiple_license_test/pkg/a/main.go
  test/testdata/multiple_license_test/pkg/b/main.go
  test/testdata/test-multiple.yaml
Labels: feature

#119 Prune packages before listing all dependencies
  pkg/deps/npm.go
Labels: bug
