Repository apache/skywalking-eyes, pull requests merged in 2022-09, with the labels that each got.

#132 Docker Multiple Architecture Support :fixes#9089
  .github/workflows/publish-docker.yaml
  Makefile
Labels: feature

#134 Polish maven test for convenient debug
  LICENSE
  pkg/deps/jar_test.go
  pkg/deps/maven_test.go
  pkg/deps/testdata/maven/.mvn/wrapper/maven-wrapper.properties
  pkg/deps/testdata/maven/mvnw
Labels: enhancement

#133 feat: list files by git when possible
  Makefile
  go.mod
  go.sum
  pkg/header/check.go
  pkg/header/check_test.go
  pkg/header/config.go
Labels: enhancement

#135 Switch to npm ci for reliable builds
  pkg/deps/npm.go
Labels: enhancement

#136 Fix optional dependencies are not excluded
  pkg/deps/maven.go
  pkg/deps/maven_test.go
Labels: bug, dep / maven

#137 Fix exclude not work for transitive dependencies and add recursive config
  README.md
  pkg/deps/cargo.go
  pkg/deps/config.go
  pkg/deps/golang.go
  pkg/deps/maven.go
Labels: bug, dep / maven

#140 dep: do not write license files if they already exist
  commands/deps_resolve.go
Labels: dep / core
