Repository apache/skywalking-eyes, pull requests merged in 2022-04, with the labels that each got.

#98 New feature: replace already existing license header based on pattern
  README.md
  commands/header_fix.go
  pkg/header/config.go
  pkg/header/fix.go
  pkg/header/fix_test.go
  pkg/review/header.go
Labels: feature

#100 Add Python DocString comment style
  assets/styles.yaml
Labels: enhancement

#101 Add .exe suffix to windows binary
  .gitignore
  Makefile
Labels: bug

#102 Support fix license header for tcl files
  assets/languages.yaml
Labels: enhancement
