Repository apache/skywalking-eyes, pull requests merged in 2022-07, with the labels that each got.

#120 Support license expression in dep check.
  pkg/deps/check.go
  pkg/deps/check_test.go
Labels: feature

#121 Add rust cargo support for dep command.
  Dockerfile
  pkg/deps/cargo.go
  pkg/deps/cargo_test.go
  pkg/deps/resolve.go
Labels: enhancement, feature

#124 Draft 0.4.0
  CHANGES.md
  action.yml
Labels: chore

#125 feat(header templates): add support for AGPL-3.0
  assets/header-templates/AGPL-3.0-only.txt
  assets/header-templates/AGPL-3.0-or-later.txt
Labels: enhancement

#126 Upgrade go version to 1.18
  .github/workflows/license-eye-check.yaml
  Dockerfile
  Makefile
  go.mod
  go.sum
Labels: chore

#127 Add MulanPSL-2.0 support.
  README.md
  assets/header-templates/MulanPSL-2.0.txt
  pkg/header/config.go
  pkg/header/config_test.go
Labels: feature
