Repository apache/skywalking-eyes, pull requests merged in 2022-02, with the labels that each got.

#89 Add comment style for HCL (Terraform)
  assets/languages.yaml
Labels: enhancement

#90 Add comment style for Makefile & EditorConfig
  assets/languages.yaml
Labels: enhancement

#91 config: Fix incorrect log message
  pkg/config/config.go
Labels: chore

#92 test: add tests for bare spdx license header content
  test/content_test.go
  test/testdata/spdx_content_test/testcase.go
  test/testdata/spdx_content_test/testcase.graphql
  test/testdata/spdx_content_test/testcase.ini
  test/testdata/spdx_content_test/testcase.java
  test/testdata/spdx_content_test/testcase.ml
  test/testdata/spdx_content_test/testcase.php
  test/testdata/spdx_content_test/testcase.pl
  test/testdata/spdx_content_test/testcase.py
  test/testdata/spdx_content_test/testcase.pyx
  test/testdata/spdx_content_test/testcase.sh
  test/testdata/spdx_content_test/testcase.yaml
  test/testdata/spdx_content_test/testcase.yml
  test/testdata/test-spdx-content.yaml
Labels: test
